version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/symfony/app/

hooks:
  AfterInstall:
    - location: script/install_dependencies
      timeout: 900
      runas: root
    - location: script/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server
      timeout: 300
      runas: root

